backend:
  name: github
  repo: makav007-iNKSTECHSHUB/ZaiLVEXONATED
  branch: main
media_folder: images
public_folder: /images
collections:
  - name: gallery
    label: Infinite Stream Gallery
    folder: images
    create: true
    slug: '{{slug}}'
    fields:
      - label: Display Title
        name: title
        widget: string
      - label: Upload Photo
        name: image
        widget: image
        
